/**
 * State Factory for the Sbobuz game engine.
 *
 * Creates the initial GameState (State_0) from a player list, RNG seed, and
 * game configuration. Performs: deck creation -> shuffle -> deal -> starting
 * player selection. Runs exactly once per game at the transition from lobby
 * to gameplay.
 *
 * This is a pure function. Given the same inputs, it produces the same
 * initial state every time. All randomness flows through the seeded RNG.
 *
 * @see SBOBUZ_ENGINE_SPEC.md Section 4 (Setup & Deal)
 * @see docs/specs/engine/state-factory.md
 */

import type { GameConfig, GameState } from '@shared/game-state.js';

import { createDeck, dealCards, shuffleDeck } from './deck.js';
import { createRng } from './rng.js';
import { determineStartingPlayer } from './starting-player.js';

// ---------------------------------------------------------------------------
// Types owned by this component
// ---------------------------------------------------------------------------

/**
 * Input required to create a new game.
 */
export interface CreateGameInput {
  /** Unique game identifier, generated by the caller (Lobby Module). */
  readonly gameId: string;

  /** Player IDs in seating order (determines turnOrder). Must be 2-5 players. */
  readonly playerIds: ReadonlyArray<string>;

  /** The seed for the PRNG. Determines deck shuffle and starting player tiebreaker. */
  readonly seed: number;

  /** Game configuration from room settings. */
  readonly config: GameConfig;
}

// ---------------------------------------------------------------------------
// Validation
// ---------------------------------------------------------------------------

/**
 * Validates the CreateGameInput and throws descriptive errors for invalid inputs.
 *
 * @param input - The game creation parameters to validate.
 * @throws {Error} If any validation rule is violated.
 */
function validateInput(input: CreateGameInput): void {
  // Game ID validation
  if (input.gameId.length === 0) {
    throw new Error('INVALID_GAME_ID: game ID must be non-empty string');
  }

  // Player count validation
  if (input.playerIds.length < 2 || input.playerIds.length > 5) {
    throw new Error(
      `INVALID_PLAYER_COUNT: must be 2-5 players, got ${String(input.playerIds.length)}`,
    );
  }

  // Player ID non-empty validation
  for (const id of input.playerIds) {
    if (id.length === 0) {
      throw new Error('INVALID_PLAYER_ID: player ID must be non-empty string');
    }
  }

  // Duplicate player ID validation
  const uniqueIds = new Set(input.playerIds);
  if (uniqueIds.size !== input.playerIds.length) {
    throw new Error('DUPLICATE_PLAYER_ID: player IDs must be unique');
  }

  // Seed validation
  if (!Number.isFinite(input.seed)) {
    throw new Error('INVALID_SEED: seed must be a finite number');
  }

  // Config validation
  if (input.config.turnTimerSeconds <= 0) {
    throw new Error('INVALID_CONFIG: turnTimerSeconds must be positive');
  }
  if (input.config.disconnectGraceSeconds <= 0) {
    throw new Error('INVALID_CONFIG: disconnectGraceSeconds must be positive');
  }
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Creates the initial game state for a new Sbobuz game.
 *
 * Performs: deck creation -> shuffle -> deal -> starting player selection.
 *
 * The resulting state has:
 * - phase = 'playing'
 * - turnDirection = 1 (forward)
 * - freePlay = false
 * - nextCardOverride = null
 * - actionCount = 0
 * - playPile = [] (empty)
 * - burnPile = [] (empty)
 *
 * @param input - The game creation parameters.
 * @returns The initial GameState (State_0), ready for the first player's turn.
 * @throws {Error} If input validation fails (wrong player count, invalid seed, etc.).
 *
 * @example
 * ```typescript
 * const state = createInitialState({
 *   gameId: 'game-123',
 *   playerIds: ['alice', 'bob'],
 *   seed: 42,
 *   config: {
 *     turnTimerSeconds: 30,
 *     disconnectGraceSeconds: 30,
 *     maxPlayers: 5,
 *     minPlayers: 2,
 *   },
 * });
 * // state.phase === 'playing'
 * // state.players.length === 2
 * // state.drawPile.length === 36
 * ```
 */
export function createInitialState(input: CreateGameInput): GameState {
  validateInput(input);

  // Step 1: Create the standard 54-card deck
  const deck = createDeck();

  // Step 2: Shuffle with seeded RNG
  let rng = createRng(input.seed);
  const { value: shuffledDeck, nextRng: rngAfterShuffle } = shuffleDeck(deck, rng);
  rng = rngAfterShuffle;

  // Step 3: Deal cards to players
  const { players, drawPile } = dealCards(shuffledDeck, input.playerIds);

  // Step 4: Determine starting player
  const { startingIndex } = determineStartingPlayer(players, rng);

  // Step 5: Assemble initial state
  return {
    gameId: input.gameId,
    phase: 'playing',
    config: input.config,

    drawPile,
    playPile: [],
    burnPile: [],

    players,
    turnOrder: [...input.playerIds],
    currentPlayerIndex: startingIndex,
    turnDirection: 1,

    freePlay: false,
    nextCardOverride: null,

    rngSeed: input.seed,
    actionCount: 0,
  };
}
